// <auto-generated />
namespace VideoShare.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class adduserRefferencetoQueryRemove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduserRefferencetoQueryRemove));
        
        string IMigrationMetadata.Id
        {
            get { return "202209111026031_adduserRefferencetoQueryRemove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
